# Generated by Django 4.0.4 on 2022-05-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
    ]
