# Generated by Django 4.0.4 on 2022-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
