# Generated by Django 4.0.4 on 2022-05-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('customer', '0002_alter_customer_addressid'),
        ('park', '0001_initial'),
        ('vacation_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_plan',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='vacation_plan',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='vacation_plan',
            name='park',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='park.park'),
        ),
    ]
