# Generated by Django 4.0.4 on 2022-05-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacation_plan', '0002_alter_vacation_plan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_plan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
