# Generated by Django 4.0.4 on 2022-05-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_addon_addon_price_addon_user'),
        ('vacation_plan', '0003_vacation_plan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_plan',
            name='addons',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='addon.addon'),
        ),
    ]
