# Generated by Django 4.0.4 on 2022-05-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_plan', '0004_vacation_plan_addons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation_plan',
            old_name='addons',
            new_name='addon',
        ),
    ]
