# Generated by Django 4.0.4 on 2022-05-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addons',
            new_name='Addon',
        ),
    ]
