# Generated by Django 4.0.4 on 2022-05-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_addon_addon_price_addon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='addon_price',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='user',
        ),
    ]
