# Generated by Django 4.0.4 on 2022-05-09 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addon', '0005_remove_addon_addon_price_remove_addon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='addon_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AddField(
            model_name='addon',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
